config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root 'pins#index'

     resources :pins do
        member do
          put "like", to: "pins#upvote"
        end
      end

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	acts_as_votable
	belongs_to :user

	has_attached_file :image, styles: { medium:"300x300>"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
	before_action :authenticate_user!, except:[:index, :show]
	def index 
		@pins = Pin.all.order("created_at DESC")
	end

	def new
		@pin = current_user.pins.build
	end

	def create
		@pin = current_user.pins.build(pin_params)
		if @pin.save
			redirect_to @pin, notice: "Exito creado el nuevo Pin"
		else
			render 'new'			
		end
	end

	def show
	end

	def edit
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Exito Actualizado el nuevo Pin"
		else
			render 'edit'			
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end

	def upvote
		@pin.upvote_by current_user
		redirect_to :back
		
	end

	private

	def pin_params
		params.require(:pin).permit(:titulo, :descrip, :image)
	end

	def find_pin
		@pin = Pin.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_nav.html.erb
<nav id= "navbar" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Boton Navegador</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to "Pinear", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
      <ul class="nav navbar-nav">
        <li > <%= link_to " Nuevo Pin",new_pin_path, class:"glyphicon glyphicon-book" %> </li>
            
      </ul>


    

      <ul class="nav navbar-nav navbar-right">
       
        <li><%= link_to " Sign Out", destroy_user_session_path, method: :delete,  class:"glyphicon glyphicon-off" %></li>

        <li><%= link_to " Cambiar Password", edit_user_registration_path, class:"glyphicon glyphicon-edit" %></li>


      </ul>


    <% else %>

        <ul class="nav navbar-nav navbar-right">
       
        <li><%= link_to " Registrate", new_user_registration_path, class:"glyphicon glyphicon-plus" %></li>
        <li><%= link_to " Sign in", new_user_session_path, class:"glyphicon glyphicon-user" %></li>

      </ul>

    <% end %>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PinBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/nav' %>

	<div class="container-fluid">	

	<% flash.each do |name, msg|%>
		<%= content_tag :div, msg, class: "alert alert-info" %>
	<% end %>

	<%= yield %>

	</div>
	
</body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin, html: { multipart: true } do |f| %>
	<% if @pin.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@pin.errors.count, "error") %> Prohíbe guardar los datos:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 

  <div class="form-group">
    <%=f.input :image, as: :file %>
  </div>

	<div class="form-group">
	 <%=f.input :titulo, input_html:{class: 'form-control'} %>
	</div>		

	<div class="form-group">
	 <%=f.input :descrip, input_html:{class: 'form-control'} %>
	</div>

	<%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/pins/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="row">

		<div class="panel panel-default">
			<div class="panel-heading">
				<h1> Editar</h1>

			</div>
			<div class="panel-body">

				<%= image_tag @pin.image.url(:medium) %>
				<%= render 'form' %>



			</div>

			<div class="panel-footer">
				<%= link_to "Atras", pin_path  %>
			</div>

		</div>


	</div>
	
</div> 

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">

	<% @pins.each do |p| %>
		<div class="box panel panel-default">	
			
			<%= link_to (image_tag p.image.url), p %>
			
			<div class="panel-body">
				<h2> <%= link_to p.titulo, p %> </h2>
				<p class="user">
					Pineado por:
					<%= p.user.email %>
				</p>	
			</div>
		</div>
	<% end %>
	

</div>

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="row">

		<div class="panel panel-default">
			<div class="panel-heading">
				<h1> Nuevo Pin</h1>

			</div>
			<div class="panel-body">
				<%= render 'form' %>


			</div>

		</div>


	</div>
	
</div> 

app/views/pins/show.html.erb
<div id="pin_show" class="row">
	<div class="col-md-8 col-md-offset-2">

		<div class="panel panel-default">

			<div class="panel-heading">

				<div class="pin_image">
					<%= image_tag @pin.image.url %>
				</div>
			</div>
				<div class="panel-body">

					<h1> <%= @pin.titulo %></h1>
					<p class="description"> <%= @pin.descrip %> </p>
					<br>
					Subido por
					<%= @pin.user.email %>

				</div>
				<div class="panel-footer">
						<div class="row">
							<div class="col-md-12">
								<div class="btn-group pull-right">

							<%= link_to like_pin_path(@pin), method: :put, class:"btn btn-default" do %> <span class="glyphicon glyphicon-heart"> <%= @pin.get_upvotes.size %> </span> 
							<% end %>
							
							<%= link_to "Editar", edit_pin_path, class:"btn btn-default" %>
							<%= link_to "Borrar", pin_path,class:"btn btn-default", method: :delete, data: {confirm: "Esta seguro"} %>
							</div>
						</div>
					</div>

					
				</div>


			</div>
		</div>

</div>